GET http://localhost:3000/profile

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "liki",
    "password": "liki"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "liki",
    "email": "liki@a",
    "password": "liki"
}
